repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Update this to the version you want
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
    - id: black
      language_version: python3.9

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4  # Update this to the version you want
    hooks:
    -   id: isort
